### ISSUE TITLE
Course 3 started last week, can you upload the lecture notebook ? Thank you

### ISSUE THREAD

**Issue by linhanxiao** [ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization#56] opened 2020-08-07 12:38 UTC
Course 3 started last week, can you upload the lecture notebook ? Thank you

**Comment by linhanxiao** [comment] 2020-08-07 12:39
not only the assignment notebook

**Comment by ijelliti** [comment] 2020-08-07 14:27
hi @linhanxiao,
I uploaded the lectures slides with the assignment notebook(original+solution) [here](https://github.com/ijelliti/Deeplearning.ai-Natural-Language-Processing-Specialization/tree/master/3%20-%20Natural%20Language%20Processing%20with%20Sequence%20Models)

**Comment by ijelliti** [comment] 2020-08-07 14:28
Duplicate of #50

**Closed** 2020-08-07 14:28 UTC
